//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPharmacy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Product
    {
        public int id { get; set; }
        [DisplayName("Product ID")]
        public string product_id { get; set; }
        [DisplayName("Product Name")]

        public string product_name { get; set; }
        [DisplayName("Purchase Price")]

        public string purchase_prx { get; set; }
        [DisplayName("Manufacturing Price")]

        public string msr_prx { get; set; }
        [DisplayName("Manufacturer")]

        public string manufacturer { get; set; }
    }

    public partial class ProductToDisplay
    {
        public int id { get; set; }
        [DisplayName("Product ID")]
        public string product_id { get; set; }
        [DisplayName("Product Name")]
        public string product_name { get; set; }
        [DisplayName("Purchase Price")]
        public decimal purchase_prx { get; set; }
        [DisplayName("Manufacturing Price")]
        public string msr_prx { get; set; }
        [DisplayName("Manufacturer")]
        public string manufacturer { get; set; }
    }


}
